/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Cpu.c
**     Project     : flexio_qc01
**     Processor   : MK82FN256VLL15
**     Component   : MK82FN256LL15
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0 MK82FN256xxx15
**     Datasheet   : K82P121M150SF5RM, Rev. 0, May 2015
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-04-20, 19:37, # CodeGen: 36
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         SystemInit            - void SystemInit(void);
**         SystemCoreClockUpdate - void SystemCoreClockUpdate(void);
**
**     (c) Freescale Semiconductor, Inc.
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */

/* {Default RTOS Adapter} No RTOS includes */
#include "Cpu.h"
#include "Events.h"


#ifdef __cplusplus
extern "C" {
#endif

/*
** ===================================================================
**     Method      :  Common_Init (component MK82FN256LL15)
**     Description :
**         Initialization of registers for that there is no 
**         initialization component.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#if CPU_COMMON_INIT
void Common_Init(void)
{
}

#endif /* CPU_COMMON_INIT */
/*
** ===================================================================
**     Method      :  Components_Init (component MK82FN256LL15)
**     Description :
**         Initialization of components (with exception for Peripheral
**         Initialization Components which are initialized in 
**         Peripherals_Init() method).
**         For example, if automatic initialization feature 
**         is enabled in LDD component then its Init method call 
**         is executed in Components_Init() method.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#if CPU_COMPONENTS_INIT
void Components_Init(void)
{

  /*! pitTimer1 Auto initialization start */
  PIT_DRV_Init(pitTimer1_IDX,true);
  PIT_DRV_InitChannel(pitTimer1_IDX,pitTimer1_CHANNEL,&pitTimer1_InitConfig0);
  PIT_DRV_StartTimer(pitTimer1_IDX,pitTimer1_CHANNEL);
  /*! pitTimer1 Auto initialization end */
  /*! gpio1 Auto initialization start */
  GPIO_DRV_Init(gpio1_InpConfig0,gpio1_OutConfig0);
  /*! gpio1 Auto initialization end */
  
  /*! DbgCs1 Auto initialization start */
  /* Enable clock source for LPUART - bitfield LPUART0SRC within SIM_SOPT2 */
  CLOCK_SYS_SetLpuartSrc(BOARD_DEBUG_UART_INSTANCE,kClockLpuartSrcPllFllSel);
  /* Debug console initialization */
  DbgConsole_Init(BOARD_DEBUG_UART_INSTANCE, DEBUG_UART_BAUD, DEBUG_UART_TYPE);
  /*! DbgCs1 Auto initialization end */
  /*! dmaController1 Auto initialization start */
  EDMA_DRV_Init(&dmaController1_State,&dmaController1_InitConfig0);
  /*! dmaController1 Auto initialization end */
  
  /*! flexibleIO1 Auto initialization start */
  CLOCK_SYS_SetFlexioSrc(flexibleIO1_IDX, kClockFlexioSrcOsc0erClk);
  FLEXIO_DRV_Init(flexibleIO1_IDX, &flexibleIO1_initConfig0);
  FLEXIO_DRV_Start(flexibleIO1_IDX);
  /*! flexibleIO1 Auto initialization end */
    
  /*! flexTimer1 Auto initialization start */
  FTM_DRV_Init(flexTimer1_IDX,&flexTimer1_InitConfig0);
  FTM_DRV_SetClock(flexTimer1_IDX, kClock_source_FTM_SystemClk, kFtmDividedBy1);
  FTM_DRV_PwmStart(flexTimer1_IDX,&flexTimer1_ChnConfig1,0U);
  FTM_DRV_PwmStart(flexTimer1_IDX,&flexTimer1_ChnConfig1,1U);
  FTM_DRV_PwmStart(flexTimer1_IDX,&flexTimer1_ChnConfig2,2U);
  FTM_DRV_PwmStart(flexTimer1_IDX,&flexTimer1_ChnConfig3,3U);
  FTM_DRV_PwmStart(flexTimer1_IDX,&flexTimer1_ChnConfig4,4U);
  FTM_DRV_PwmStart(flexTimer1_IDX,&flexTimer1_ChnConfig5,5U);
  FTM_DRV_PwmStart(flexTimer1_IDX,&flexTimer1_ChnConfig7,7U);
  FTM_DRV_SetTimeOverflowIntCmd(flexTimer1_IDX,false);
  FTM_DRV_SetFaultIntCmd(flexTimer1_IDX,false);
  /*! flexTimer1 Auto initialization end */
  
  /*! tpmTmr1 Auto initialization start */
  TPM_DRV_Init(tpmTmr1_IDX, &tpmTmr1_InitConfig0);
  TPM_DRV_SetClock(tpmTmr1_IDX, kTpmClockSourceModuleClk, kTpmDividedBy1);
  TPM_DRV_PwmStart(tpmTmr1_IDX, &tpmTmr1_ChnConfig0, 0U);
  /*! tpmTmr1 Auto initialization end */
  
  /*! servo_loop_timer Auto initialization start */
  PIT_DRV_Init(servo_loop_timer_IDX,true);
  PIT_DRV_InitChannel(servo_loop_timer_IDX,servo_loop_timer_CHANNEL,&servo_loop_timer_InitConfig0);
  PIT_DRV_StartTimer(servo_loop_timer_IDX,servo_loop_timer_CHANNEL);
  /*! servo_loop_timer Auto initialization end */
}
#endif /* CPU_COMPONENTS_INIT */


#ifdef __cplusplus
}
#endif

/* END Cpu. */

